-- MySQL Script generated by MySQL Workbench
-- Wed May 17 11:01:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dropbox
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dropbox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dropbox` DEFAULT CHARACTER SET utf8 ;
USE `dropbox` ;

-- -----------------------------------------------------
-- Table `dropbox`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dropbox`.`user` (
  `oId` INT(11) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`oId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dropbox`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dropbox`.`file` (
  `oId` INT(11) NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  `ownerID` INT NOT NULL,
  PRIMARY KEY (`oId`),
  INDEX `fk_file_user1_idx` (`ownerID` ASC),
  CONSTRAINT `fk_file_user1`
    FOREIGN KEY (`ownerID`)
    REFERENCES `dropbox`.`user` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dropbox`.`filepermission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dropbox`.`filepermission` (
  `oid` INT(11) NOT NULL,
  `read` TINYINT(1) NOT NULL,
  `write` TINYINT(1) NOT NULL,
  `fileID` INT NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`oid`),
  INDEX `fk_filepermission_file1_idx` (`fileID` ASC),
  INDEX `fk_filepermission_user1_idx` (`userID` ASC),
  CONSTRAINT `fk_filepermission_file1`
    FOREIGN KEY (`fileID`)
    REFERENCES `dropbox`.`file` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filepermission_user1`
    FOREIGN KEY (`userID`)
    REFERENCES `dropbox`.`user` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dropbox`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dropbox`.`group` (
  `oId` INT(11) NOT NULL,
  `groupName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`oId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dropbox`.`usergroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dropbox`.`usergroup` (
  `oId` INT(11) NOT NULL,
  `userId` INT(11) NOT NULL,
  `groupId` INT(11) NOT NULL,
  PRIMARY KEY (`oId`),
  INDEX `fk_Usergroup_user_idx` (`userId` ASC),
  INDEX `fk_Usergroup_group1_idx` (`groupId` ASC),
  CONSTRAINT `fk_Usergroup_group1`
    FOREIGN KEY (`groupId`)
    REFERENCES `dropbox`.`group` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usergroup_user`
    FOREIGN KEY (`userId`)
    REFERENCES `dropbox`.`user` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
