-- MySQL Script generated by MySQL Workbench
-- Wed May 17 11:01:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usertable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usertable` (
  `oId` INT(11) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`oId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`filetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filetable` (
  `oId` INT(11) NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  `ownerID` INT NOT NULL,
  PRIMARY KEY (`oId`),
  INDEX `fk_filetable_usertable1_idx` (`ownerID` ASC),
  CONSTRAINT `fk_filetable_usertable1`
    FOREIGN KEY (`ownerID`)
    REFERENCES `mydb`.`usertable` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`filepermissionstable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filepermissionstable` (
  `oid` INT(11) NOT NULL,
  `read` TINYINT(1) NOT NULL,
  `write` TINYINT(1) NOT NULL,
  `fileID` INT NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`oid`),
  INDEX `fk_filepermissionstable_filetable1_idx` (`fileID` ASC),
  INDEX `fk_filepermissionstable_usertable1_idx` (`userID` ASC),
  CONSTRAINT `fk_filepermissionstable_filetable1`
    FOREIGN KEY (`fileID`)
    REFERENCES `mydb`.`filetable` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filepermissionstable_usertable1`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`usertable` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`grouptable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grouptable` (
  `oId` INT(11) NOT NULL,
  `groupName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`oId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usergrouptable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usergrouptable` (
  `oId` INT(11) NOT NULL,
  `userId` INT(11) NOT NULL,
  `groupId` INT(11) NOT NULL,
  PRIMARY KEY (`oId`),
  INDEX `fk_UserGroupTable_UserTable_idx` (`userId` ASC),
  INDEX `fk_UserGroupTable_GroupTable1_idx` (`groupId` ASC),
  CONSTRAINT `fk_UserGroupTable_GroupTable1`
    FOREIGN KEY (`groupId`)
    REFERENCES `mydb`.`grouptable` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserGroupTable_UserTable`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`usertable` (`oId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
